# Generated by Django 5.2.4 on 2025-07-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plan_picture_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(choices=[('walk', '徒歩'), ('train', '電車'), ('bus', 'バス'), ('shinkansen', '新幹線'), ('plane', '飛行機'), ('car', '車'), ('other', 'その他')], max_length=20)),
                ('transportation_icon_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_methods', to='app.plan')),
            ],
        ),
    ]
