# Generated by Django 5.2.4 on 2025-07-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transportationmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationmethod',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='app.transportationmethod'),
        ),
        migrations.AlterField(
            model_name='transportationmethod',
            name='transportation',
            field=models.CharField(choices=[('walk', '徒歩'), ('train', '電車'), ('bus', 'バス'), ('shinkansen', '新幹線'), ('plane', '飛行機'), ('car', '車'), ('other', 'その他')], max_length=20, unique=True),
        ),
    ]
