# Generated by Django 5.2.4 on 2025-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_transportationmethod_plan_plan_transportation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationmethod',
            name='transportation_icon_url',
        ),
        migrations.AddField(
            model_name='transportationmethod',
            name='transportation_icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
