# Generated by Django 5.2.4 on 2025-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
