# Generated by Django 5.0.6 on 2026-04-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_packing_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packing_item',
            new_name='PackingItem',
        ),
    ]
